FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y curl; apt-get install -y kafkacat
RUN apt-get install -y jq; apt-get install -y bsdmainutils 
# install mongosh
RUN curl https://downloads.mongodb.com/compass/mongodb-mongosh_1.0.0_amd64.deb -o mongosh.deb && \
    dpkg --install mongosh.deb
COPY tutorial-scripts/initialize-container.sh /
RUN chmod +x initialize-container.sh

# Modify command prompt
RUN echo 'PS1="\[\e[32m\][\e[mMongoDB Kafka Connector Tutorial\e[32m]\e[m : "' >> ~/.bashrc

# Add welcome text
COPY greeting.sh tutorial-scripts/status.sh /
RUN chmod +x status.sh
RUN cat greeting.sh >> ~/.bashrc

# Cleanup
RUN rm mongosh.deb
RUN rm greeting.sh
